version: 0.2

phases:
    install:
        commands:
            #testing 
            # Purely informational
            - aws --version
            # Upgrade pip
            - pip install --upgrade pip
            # Upgrade to the latest version of awscli because the one bundled with
            # the CodeBuild image has a bug that prevents SAM templates from
            # packaging correctly.
            - pip install --upgrade awscli
    pre_build:
        commands:
            # Loop through directory structure and pip install all function libraries
            # as specified in their respective requirements.txt
            - for dir in lambdafunctions/*; do echo "$dir"; if [ -f "$dir"/requirements.txt ]; then (pip install -t "$dir"/requirements.txt); fi; done
    build:
        commands:
              #- cd lambdafunctions; for dir in *; do echo "this is *****>> $dir"; if [ -f "$dir"/requirements.txt ]; then (cd $dir; zip -r ../"$dir"_package.zip *); fi; done
              #- for dir in lambdafunctions/*; do echo "this is *****>>>> $dir"; if [ -f "$dir"/requirements.txt ]; then (cd lambdafunctions ; zip -r ../"$dir"_package.zip *); fi; done
              
             - mkdir build-output
             - find . -type d -name lambdafunctions -exec cp -R {} build-output \;
             - cd build-output/lambdafunctions; for dir in *; do echo "this is *****>> $dir"; if [ -f "$dir"/requirements.txt ]; then (cd $dir; zip -r ../"$dir".zip *); fi; done
             # - find . -mindepth 1 -name build-output -prune -o -exec rm -rf {} +
             # testing

artifacts:
  files:
    - '**/*'
  base-directory: 'build-output/lambdafunctions'
  discard-paths: yes
  secondary-artifacts:
    artifact1:
      files:
        - build-output/lambdafunctions/github-to-lambda-demo-main.zip
      discard-paths: no
