version: 0.2

phases:
    install:
        commands:
            #testing 
            # Purely informational
            - aws --version
            # Upgrade pip
            - pip install --upgrade pip
            # Upgrade to the latest version of awscli because the one bundled with
            # the CodeBuild image has a bug that prevents SAM templates from
            # packaging correctly.
            - pip install --upgrade awscli
    pre_build:
        commands:
            # Loop through directory structure and pip install all function libraries
            # as specified in their respective requirements.txt
            - for dir in lambdafunctions/*; do echo "$dir"; if [ -f "$dir"/requirements.txt ]; then (pip install -t "$dir"/requirements.txt); fi; done
    build:
        commands:
              - cd lambdafunctions; for dir in *; do echo "this is *****>> $dir"; if [ -f "$dir"/requirements.txt ]; then (cd $dir; zip -r ../"$dir"_package.zip *); fi; done
              #- for dir in lambdafunctions/*; do echo "this is *****>>>> $dir"; if [ -f "$dir"/requirements.txt ]; then (cd lambdafunctions ; zip -r ../"$dir"_package.zip *); fi; done

artifacts:
  files:
    - '**/*'
  base-directory: 'lambdafunctions'
  discard-paths: no
  type: zip
