version: 0.2

phases:
    install:
        commands:
            #testing 
            # Purely informational
            - aws --version
            # Upgrade pip
            #- pip install --upgrade pip
            # Upgrade to the latest version of awscli because the one bundled with
            # the CodeBuild image has a bug that prevents SAM templates from
            # packaging correctly.
            #- pip install --upgrade awscli
    pre_build:
        commands:
            # Loop through directory structure and pip install all function libraries
            # as specified in their respective requirements.txt
            #- for dir in lambdafunctions/*; do echo "$dir"; if [ -f "$dir"/requirements.txt ]; then (pip install -t "$dir"/requirements.txt); fi; done
            - cd lambdafunctions; for function_name in */; do zip -r "${function_name%/}.zip" "$function_name"; done
            - echo " displaying directories "
            - pwd
            - ls -1
    build:
        commands:
              #- cd lambdafunctions; for dir in *; do echo "this is *****>> $dir"; if [ -f "$dir"/requirements.txt ]; then (cd $dir; zip -r ../"$dir"_package.zip *); fi; done
              #- for dir in lambdafunctions/*; do echo "this is *****>>>> $dir"; if [ -f "$dir"/requirements.txt ]; then (cd lambdafunctions ; zip -r ../"$dir"_package.zip *); fi; done
              
             #- mkdir build-output
             #- find . -type d -name lambdafunctions -exec cp -R {} build-output \;
             # - cd build-output/lambdafunctions; for dir in *; do echo "this is *****>> $dir"; if [ -f "$dir"/requirements.txt ]; then (cd $dir; zip -r ../"$dir".zip *); fi; done
             # - find . -mindepth 1 -name build-output -prune -o -exec rm -rf {} +
             - echo " testing zipping files "

artifacts:
  files:
    - '**/*'
  base-directory: 'lambdafunctions'
  discard-paths: yes
  secondary-artifacts:
    artifact1:
      files:
        - lambdafunctions/generate-presigned-S3url.zip
        - lambdafunctions/get-import-process-status.zip
        - lambdafunctions/github-to-lambda-demo-main.zip
        - lambdafunctions/register-exposure-upload.zip
        - lambdafunctions/save-exposure-subset.zip
        - lambdafunctions/save-user-settings.zip
      discard-paths: no
