version: 0.2

phases:
    install:
        commands:
            #testing 
            # Purely informational
            - aws --version
            # Upgrade pip
            - pip install --upgrade pip
            # Upgrade to the latest version of awscli because the one bundled with
            # the CodeBuild image has a bug that prevents SAM templates from
            # packaging correctly.
            - pip install --upgrade awscli
    pre_build:
        commands:
            # Loop through directory structure and pip install all function libraries
            # as specified in their respective requirements.txt
            - for dir in lambdafunctions/*; do echo "$dir"; if [ -f "$dir"/requirements.txt ]; then (pip install -t "$dir"/vendored/ -r "$dir"/requirements.txt); fi; done
    build:
        commands:
            # Create CFN change set
            # - aws cloudformation create-change-set --template-url https://$S3_BUCKET.s3.amazonaws.com/$STAGE_NAME/config/sam-output.yaml --parameters file://cfn-config.json --role-arn arn:aws:iam::$AWS_ACCOUNT_NUMBER:role/$CFN_ROLE --change-set-name tailor-$STAGE_NAME-ChangeSet --stack-name tailor-$STAGE_NAME --capabilities CAPABILITY_IAM
            
              - for dir in lambdafunctions/*; do echo "$dir"; if [ -f "$dir"/requirements.txt ]; then (cd $dir ; zip -r ../"$dir"_package.zip *); fi; done
